name: "medical_warehouse"
version: "1.0.0"
config-version: 2

profile: "medical_warehouse"

model-paths: ["models"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  medical_warehouse:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table

